<?php 
mysqli_query($con, "UPDATE pwd_table SET 
			pwd_number='$pwd_number',
			date_applied='$date_applied',
			pwd_lastname='$pwd_lastname',
			pwd_firstname='$pwd_firstname',
			pwd_middlename='$pwd_middlename',
			pwd_suffix='$pwd_suffix',
			pwd_birthday='$pwd_birthday',
			pwd_age='$pwd_age',
			pwd_birthplace='$pwd_birthplace',
			pwd_sex='$sex',
			pwd_religion='$pwd_religion',
			pwd_ethnic_group='$pwd_ethnic',
			pwd_civil_status='$pwd_civilStatus',
			pwd_blood_type='$pwd_bloodType',
			pwd_disability_type='$disability_type',
			pwd_disability_cause='$disability_cause',
			pwd_house_street='$pwd_street',
			pwd_barangay='$pwd_barangay',
			pwd_landline='$pwd_landline',
			pwd_mobile='$pwd_mobile',
			pwd_email='$pwd_email',
			pwd_education='$pwd_education',
			pwd_employment_status='$pwd_employmentStatus',
			pwd_employment_category='$pwd_employmentCategory',
			pwd_employment_type='$pwd_employmentType',
			pwd_occupation='$pwd_occupation',
			pwd_organization='$pwd_organization',
			pwd_organization_contact='$pwd_organizationPerson',
			pwd_organization_address='$pwd_organizationAddress',
			pwd_organization_telephone='$pwd_organizationTelephone',
			pwd_sss='$pwd_sss',
			pwd_gsis='$pwd_gsis',
			pwd_pagibig='$pwd_pagibig',
			pwd_philhealth='$pwd_philhealth',
			pwd_father_lastname='$pwd_fatherLastname',
			pwd_father_firstname='$pwd_fatherFirstname',
			pwd_father_middlename='$pwd_fatherMiddlename',
			pwd_mother_lastname='$pwd_motherLastname',
			pwd_mother_firstname='$pwd_motherFirstname',
			pwd_mother_middlename='$pwd_motherMiddlename',
			pwd_guardian_lastname='$pwd_guardianLastname',
			pwd_guardian_firstname='$pwd_guardianFirstname',
			pwd_guardian_middlename='$pwd_guardianMiddlename',
			accomplished_lastname='$accomplish_lastname',
			accomplished_firstname='$accomplish_firstname',
			accomplished_middlename-'$accomplish_middlename',
			reporting_unit='$reportingUnit_name',
			registration_number='$registration_number',
			pwd_living='$living',
			pwd_spouse_name='pwd_spouseName',
			pwd_spouse_age='$pwd_spouseAge',
			pwd_support='$economic_condition',
			pwd_pensioner_type='$pwd_pensionerType',
			pwd_pension_monthly='$pwd_pensionMonthly',
			pwd_income_source='$pwd_incomeSource',
			pwd_income_monthly='$pwd_incomeMonthly',
			interviewed_by='$pwd_interviewer',
			pwd_guardian_contact='$pwd_guardian_contact', 
			pwd_remarks='$pwd_remarks' where pwd_id='$id'");




UPDATE pwd_table SET pwd_number='$pwd_number',pwd_lastname='$pwd_lastname',pwd_firstname='$pwd_firstname',pwd_middlename='$pwd_middlename',pwd_suffix='$pwd_suffix',date_applied='$date_applied',pwd_birthday='$pwd_birthday',pwd_age='$pwd_age',pwd_birthplace='$pwd_birthplace',pwd_sex='$sex',pwd_religion='$pwd_religion',pwd_ethnic_group='$pwd_ethnic',pwd_civil_status='$pwd_civilStatus',pwd_blood_type=[value-15],pwd_disability_type=[value-16],pwd_disability_cause=[value-17],pwd_house_street=[value-18],pwd_barangay=[value-19],pwd_landline=[value-20],pwd_mobile=[value-21],pwd_email=[value-22],pwd_education=[value-23],pwd_employment_status=[value-24],pwd_occupation=[value-25],pwd_employment_category=[value-26],pwd_employment_type=[value-27],pwd_organization=[value-28],pwd_organization_contact=[value-29],pwd_organization_address=[value-30],pwd_organization_telephone=[value-31],pwd_sss=[value-32],pwd_gsis=[value-33],pwd_pagibig=[value-34],pwd_philhealth=[value-35],pwd_father_lastname=[value-36],pwd_father_firstname=[value-37],pwd_father_middlename=[value-38],pwd_mother_lastname=[value-39],pwd_mother_firstname=[value-40],pwd_mother_middlename=[value-41],pwd_guardian_lastname=[value-42],pwd_guardian_firstname=[value-43],pwd_guardian_middlename=[value-44],pwd_guardian_contact=[value-45],accomplished_lastname=[value-46],accomplished_firstname=[value-47],accomplished_middlename=[value-48],reporting_unit=[value-49],registration_number=[value-50],pwd_living=[value-51],pwd_spouse_name=[value-52],pwd_spouse_age=[value-53],pwd_support=[value-54],pwd_pensioner=[value-55],pwd_pensioner_type=[value-56],pwd_pension_monthly=[value-57],pwd_income_source=[value-58],pwd_income_monthly=[value-59],interviewed_by=[value-60],pwd_remarks=[value-61] WHERE pwd_id=[value-1]
?>


